site_name: Origin Documentation
theme: mkdocs
pages:
  - [index.md,               Table of Contents]
  - [setup/index.md,         Setting Up]
  - [api/index.md,           Api]
  - [foundation/index.md,    Foundation]
  - [internal/index.md,      Internal]
  - [glossary/index.md,      Glossary]
  - [glossary/versioning.md, Glossary, Semantic Versioning]
  - [glossary/depending.md,  Glossary, Depending on Origin]
